[package]
name = "stuncli"
version = "0.1.0"
authors = ["Safin Singh <safin.singh@gmail.com>"]
edition = "2018"

[dependencies]
stunlib = { path = '../stunlib' }

[[bin]]
bench = false
path = "src/main.rs"
name = "stun"
